sudo: required
dist: xenial
before_install:
  - curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
  - sudo apt-get update -qq
  - sudo apt-get install nodejs -y
  - sudo apt-get install build-essential -y

install:
  - npm install
  - npm i -g gulp
script: gulp
branches:
  only:
    - master
    - experimental
language: node_js
node_js:
  - "7.7"
