before_install:
  - sudo apt-get update -qq
  - sudo apt-get install build-essential
install:
  - sudo npm i -g node-gyp
  - npm install
branches:
  only:
    - master
    - experimental
language: node_js
node_js:
  - "7.7"
